### ISSUE TITLE
Bug: Application crash with ENOENT at trying to open invalid file links

### ISSUE THREAD

**Issue by sharky98** [c3er/mdview#45] opened 2023-10-20 20:55 UTC
I just tested out this viewer, which is exactly what I wanted! Without all the bell and whistle of an editor!

However, in my use case I had some bad links and when clicked, I get welcomed by an `Unhandled error` of `ENOENT: no such file or directory`, which is expected in my use case. However, the app just completely closes afterwards.

Proposed solution: Catch the error, show the error dialog (that is available in the debug tool menu) that the file does not exist and stay on the current page.

Regards! 😄

**Comment by c3er** [comment] 2023-10-21 10:27
Thanks for filing this issue!

I could reproduce this bug. I think it was introduced already in version 2.0.0😅 Background: versions 1.x.x opened links always in a new window, so it was to be expected that a window/instance that tried to open an invalid link, did close itself. But this behavior is really not nice if the tool tries to open a file in the same window!

You get quite a "technical" error message with stack trace and all, like in the screenshot below, right? This clearly can also be improved😅

While I may do bugfix release just for this, it will still take some weeks (not less then one week) to fix this. I hope, it's not too annoying for you until then.

![Screenshot of error message](https://github.com/c3er/mdview/assets/24460532/b8977eb6-2c82-4289-aee8-f122d07884dd)

**Comment by sharky98** [comment] 2023-10-21 13:21
No rush needed for me on my use case. It is small enough to live with this bug for the time being!

**Comment by c3er** [comment] 2023-10-29 18:25
[Version 3.0.1](https://github.com/c3er/mdview/releases/tag/v3.0.1) is now released. Sorry for the inconvenience!

BTW: I put "fault of Markdown Viewer" to the dialog's title, because this dialog is supposed to never occur. So, please don't hesitate, if you (or anybody) encounter this dialog!

**Closed by c3er** 2023-10-29 18:25 UTC
Labels: bug
