### ISSUE TITLE
File Permission error after installing 64bit setup for all users on Windows Server 2022

### ISSUE THREAD

**Issue by Er4twXz** [c3er/mdview#58] opened 2024-12-04 05:19 UTC
Obviously the program is trying to write into C:\Program Files 

C:\Users\adm>"C:\Program Files\mdview\mdview.exe"

C:\Users\adm>
[ 'C:\\Program Files\\mdview\\mdview.exe' ]
{
  filePath: 'C:\\Program Files\\mdview\\resources\\app.asar\\README.md',
  internalTarget: undefined,
  isTest: false,
  storageDir: 'C:\\Program Files\\mdview\\.data\\storage'
}
(node:11040) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, mkdir 'C:\Program Files\mdview\.data\storage'
    at mkdirSync (node:fs:1380:26)
    at t.mkdirSync (node:electron/js2c/node_init:2:12926)
    at StorageBase._initStorageDir (C:\Program Files\mdview\resources\app.asar\app\lib\main\storage.js:51:12)
    at new StorageBase (C:\Program Files\mdview\resources\app.asar\app\lib\main\storage.js:28:21)
    at new ApplicationSettings (C:\Program Files\mdview\resources\app.asar\app\lib\main\storage.js:66:1)
    at Object.loadApplicationSettings (C:\Program Files\mdview\resources\app.asar\app\lib\main\storage.js:344:33)
    at C:\Program Files\mdview\resources\app.asar\app\main.js:428:36
(Use `mdview --trace-warnings ...` to show where the warning was created)
(node:11040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

after creating the .data folder and giving full control on the folder .data and resources the program is working

**Comment by c3er** [comment] 2024-12-04 16:20
Thank you for filing this issue!

Do you mean with "64bit setup" the MSI package? Because with this, I could reproduce this issue. The EXE package works fine by storing the user data under "C:\Users\<user>\AppData\Roaming\mdview" as it should when installed via a setup package.

This will be fixed with the next release.

**Comment by Er4twXz** [comment] 2024-12-04 19:48
Thanks für the quick reply. Yes I  used the 64bit msi installer.

**Comment by xCaradhras** [comment] 2024-12-17 12:28
Oh, I just installed the MSI package and obviously got hit by the same issue. There are (dead?) processes in the task manager, but not window is coming up. Also no warning or error on command line.

**Comment by c3er** [comment] 2024-12-17 13:22
> Maybe you should remove the MSI from the release page or add a warning...?

I try to fix this bug this week. Do you still think, a warning for these packages is necessary?

**Comment by c3er** [comment] 2024-12-18 21:51
I released [version 3.2.0](https://github.com/c3er/mdview/releases/tag/v3.2.0) which should now also run properly after installing it globally via the MSI package.

**Closed by c3er** 2024-12-18 21:51 UTC
Labels: bug
