### ISSUE TITLE
Fails to load after install on M3 Sonoma v14.7

### ISSUE THREAD

**Issue by tylermonte** [c3er/mdview#59] opened 2024-12-19 23:43 UTC
mdview-3.2.0-arm64.dmg fails to load after install on M3 Sonoma v14.7. “mdview” is damaged and can’t be opened. I can open the archive after install and traverse to contents.

**Comment by c3er** [comment] 2024-12-20 13:48
Thank you for filing this issue!

I could reproduce this with the downloaded package. As far as I understand, this problem comes from Gatekeeper, which gets more and more strict with every macOS release😕 See also issue #28.

I could make it work on my machine (M1 Sequoia 15.2) with these steps:

- Allowing the app in the system settings:
    1. Open Settings
    2. Click on "Privacy and Security"
    3. Scroll down and click on "Developer Tools" (on my German system "Entwickler-Werkzeuge")
    4. Click on the plus sign `+` and add "mdview.app" to the list
- Removing the Quarantine attribute from the app:
    1. Open terminal
    2. Type `xattr -c /Applications/mdview.app`

After that, I could open the app installed from the downloaded DMG.

Note that the macOS port is still considered experimental and doesn't behave as one is used to with other macOS apps. See issue #22.

I'm closing this issue, since I cannot do much on my side, except fixing issue #28. But feel free to ask further questions here, if my suggestion doesn't work!

**Closed by c3er** 2024-12-20 13:48 UTC
Labels: needs reaction
